// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvkazxdelrlkvlcbavga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2a2F6eGRlbHJsa3ZsY2JhdmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzk0MjksImV4cCI6MjA2MzkxNTQyOX0.Z8oAME_cWQ6kIORzcyjGXPzUWvR1pZeJ0kiAVreFvrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);